from pathlib import Path

PCT_DIF_COL = "% Dif con PVP"
RAZON_SOCIAL_COL = "RAZON SOCIAL"
USUARIO_ML_COL = "USUARIO ML"
TIPO_CLIENTE_COL = "TIPO DE CLIENTE"
FECHA_COL = "FECHA"
MLA_COL = "MLA"
PRECIO_COL = "Precio"
SKU_COL = "SKU"
PVP_COL = "PVP"
ROT_COL = "ROT"
CANAL_COL = "CANAL"
MACRO_FAMILIA_COL = "MACROFAMILIA"

BACKEND_DIR = Path(__file__).parent
DATASETS_DIR = BACKEND_DIR / "datasets"
CATALOG_PATH = DATASETS_DIR / "catalog.db"
LEGACY_DB_PATH = BACKEND_DIR / "data.db"

DEFAULT_THRESHOLD = 15.0
